### ISSUE TITLE
HAL_OPTIONS_START_TOKEN should be '{?' or '{&'

### ISSUE THREAD

**Issue by SBylemans** [just-paja/hateoas-hal-link-resolver#4]
When dealing with partially filled in links by means of backend, the START token is '{&' instead of '{?'.

This does not allow filling in this link with the params by name because the START token is defined as '{?'.

Example relative link: `/api?export=shape{&filter}`

**Comment by ReadyPlayerNaN** [comment]
Hello @SBylemans, thank you for opening the issue. It makes complete sense to use `&` instead of `?` inside URL with prefilled query string.

Could you please include some link to a documentation describing this behaviour before we implement it?

**Comment by SBylemans** [comment]
Hey @just-paja 

The specification can be found here: https://tools.ietf.org/html/rfc6570#section-3.2.9.
The different expressions in templated url's can be found here: https://tools.ietf.org/html/rfc6570#section-2.2

When you wanna be completely in line with the spec, it should also be possible to resolve path parameters...

**Comment by ReadyPlayerNaN** [comment]
> When you wanna be completely in line with the spec, it should also be possible to resolve path parameters...

Yes, that is a good point. I must confess, that I never studied the spec. However, to be completely honest, I never required anything but the query parameters.

I created the functionality and tested it in bddf802, that should cover what is needed, If you need any more help, feel free to open/reopen issues or Pull Requests.

**Comment by SBylemans** [comment]
Will do, thanks for the quick service ;)
