### ISSUE TITLE
Simple string expansion

### ISSUE THREAD

**Issue by SBylemans** [just-paja/hateoas-hal-link-resolver#9]
Hello,

According to https://datatracker.ietf.org/doc/html/rfc6570#section-3.2.2 a uri template kan contain a single variable encompassed by curly braces ie `{var}`. It should be able to resolve this variable with a value.

The use case for this is to make mandatory query parameters in a link. This is for instance how spring builds up a link with a mandatory query parameter ie `http://localhost/path?mandatory={value}`

**Comment by ReadyPlayerNaN** [comment]
Thanks for the issue report. I agree that this should be fixed. Do you feel like opening a PR?

**Comment by SBylemans** [comment]
@just-paja sure, I'll try and do that somewhere this week.

**Comment by SBylemans** [comment]
@just-paja in order to achieve this functionality, the code has to change quite a lot. I'm trying to make it so the code will be expandable to future requirements that meet the URI template spec. Just so you know I'm working on it, but it takes a bit of time :D

**Comment by ReadyPlayerNaN** [comment]
@SBylemans oh. Sorry to hear that :-D If you need any help we can schedule a call and take a look at it together. Hope you don't need this to quickly fix a bug in your production app.

**Comment by SBylemans** [comment]
Hey @just-paja no it's rather a nice to have. The code is complete, just testing now. I was able to remove the dependency on qsm.

I have a question though, why is an array of links not translated? Ie: 
```
    [
      {
        href: 'http://example.com/api/users/{bar}/{foo}?param={param}',
        rel: 'edit'
      }
    ]
    
    getHalLink(links, 'edit',
      { bar: 'bar', foo: 'foo', param: ['multiple', 'params'] }) // returns http://example.com/api/users/{bar}/{foo}?param={param}
```

**Comment by SBylemans** [comment]
@just-paja my bad about the array stuff, forgot the `templated: true` property.

I made a PR here : https://github.com/just-paja/hateoas-hal-link-resolver/pull/10

**Comment by ReadyPlayerNaN** [comment]
I think this is resolved. Please reopen if necessary ;-)

**Comment by ReadyPlayerNaN** [comment]
@SBylemans thank you for your contribution
